module.exports.salon_descriptions = [
    "Elegant salon with professional stylists",
    "Trendy haircuts and vibrant colors",
    "Luxury spa and hair treatments",
    "Classic cuts, modern styles",
    "Eco-friendly salon with organic products",
    "Family-friendly, affordable haircuts",
    "Vintage vibes, retro hairstyles",
    "Gentlemen's grooming and shaves",
    "Bridal hair and makeup specialists",
    "Innovative styling and hair art",
    "Minimalist salon, focus on hair health",
    "Creative colorists, custom dye jobs",
    "High-end products, luxurious experience",
    "Fast, efficient walk-in service",
    "Hair and beauty consultancy",
    "Private styling and VIP treatment",
    "Holistic hair care and wellness",
    "Budget-friendly, quality service",
    "Urban salon with edgy cuts",
    "Tranquil environment with spa services"
]

module.exports.salon_names = [
    "Shear Elegance",
    "The Hair Haven",
    "Blissful Bangs",
    "Curl Up & Dye",
    "Mane Attraction",
    "Strands of Splendor",
    "Luxe Locks Lounge",
    "Chic Shears",
    "Glamour Garage",
    "Serene Snips",
    "Tress Temptations",
    "Crowning Glory",
    "Velvet Vibe Hair",
    "Sassy Scissors",
    "Hair Harmony",
    "Eclipse Hair"
]

const stylist_profiles = [
    "Alex - Expert in Asian hair trends",
    "Sam - Known for bold, dramatic cuts",
    "Jin - Specializes in elegant Asian styling",
    "Mia - Creative colorist, adventurous styles",
    "Lee - Precision cuts, Asian fashion focus",
    "Tara - Friendly, excels in customer care",
    "Ryu - Contemporary Asian hair artist",
    "Luna - Delicate touch, traditional styles",
    "Kai - Innovative stylist, modern Asian trends",
    "Yumi - Gentle approach, meticulous work",
    "Noah - Enjoys challenging, unique hairstyles",
    "Sara - Playful and vibrant coloring expert",
    "Ken - Traditional barber, precise and efficient",
    "Zoe - Passionate about sustainable beauty",
    "Max - Edgy styles, bold personality",
    "Lily - Specializes in natural, organic haircare",
    "Ethan - Charismatic, excels in personal grooming",
    "Ava - Friendly and welcoming, customer-focused",
    "Jack - Master of quick, efficient cuts",
    "Grace - Known for her calming, patient manner"
]